server:
  port: 8080
  servlet.context-path: /api/v1

spring:
  application:
    name: taskdock-api

  profiles:
    active: local

  datasource:
    username: ganeshpotti
    password: Ganesh@1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
#          ddl-auto: create-drop
    show-sql: true
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: false

jwt:
  secret-key: ouhwfrouhjwf0yuhoqr3huy9wfrouhowfy9hwrfouhwefi9nF2
  expiration: 86400000